Menu:

<Menu>:
	orientation: "vertical"
	
	Label:
		text: "Precaution of Precipitation"
		font_size: "50dp"
		
	Button:
		text: "Login"
		size_hint: .4, 1
		pos_hint: { "center_x": .5}
		
	Button:
		text: "Register"
		size_hint: .4, 1
		pos_hint: { "center_x": .5}
		
	Button:
		text: "Forgot Password"
		size_hint: .4, 1
		pos_hint: { "center_x": .5}
	
	Button:
		text: "Exit"
		size_hint: .125, .5
	